name: cppcheck
on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CppCheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          enable: all
          exclude_check: vendor,tools
          inconclusive: enable
          inline_suppression: enable
          platform: unix64
      - name: Publish report
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: cppcheck_report.txt
