name: Static code analysis with Cppcheck
on: [push]

jobs:
  analyse:
    name: Run Cppcheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        depth: 1
        submodules: 'recursive'
    - name: Configure CMake
      uses: lukka/run-cmake@v0.11
      with:
        cmakeAppendedArgs: -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -Wno-dev
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeBuildType: Release
        cmakeGenerator: UnixMakefiles
        buildDirectory: report
        buildWithCMake: false
    - name: Run Cppcheck
      id: run-cppcheck
      uses: Bedzior/cppcheck-action@v1.x
      with:
        debug: true
        enabled checks: all
        enable inconclusive: true
        generate report: true
        project: report/compile_commands.json
        exclude from check: -i${{ github.workspace }}/tools -i${{ github.workspace }}/vendor -itools -ivendor
    - name: Upload report
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: ${{ steps.run-cppcheck.outputs.htmlReportPath }}
